//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldStudentCredential
    {
        public long studentID { get; set; }
        public string studentUsername { get; set; }
        public string studentPassword { get; set; }
    }
}
