//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourse
    {
        public long Id { get; set; }
        public long courseID { get; set; }
        public long studentID { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<long> changedBy { get; set; }
        public Nullable<System.DateTime> changeDate { get; set; }
        public Nullable<bool> completed { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual StudentCredential StudentCredential { get; set; }
    }
}
