//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentPortalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
        public long ID { get; set; }
        public string studentName { get; set; }
        public string studentSurname { get; set; }
        public int age { get; set; }
        public int grade { get; set; }
        public Nullable<int> phoneNumber { get; set; }
        public string email { get; set; }
        public int parentPhoneNumber { get; set; }
        public string parentEmail { get; set; }
        public long studentID { get; set; }
    
        public virtual StudentCredential StudentCredential { get; set; }
    }
}
